CREATE TABLE WORKERS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    DAILY_INCOME DECIMAL(10,2)
);

INSERT INTO WORKERS (NAME, DAILY_INCOME) VALUES ('Bob', 200.0);
INSERT INTO WORKERS (NAME, DAILY_INCOME) VALUES ('Maria', 300.0);
INSERT INTO WORKERS (NAME, DAILY_INCOME) VALUES ('Alex', 250.0);