CREATE TABLE USER_ROLE(
    USER_ID BIGINT,
    ROLE_ID BIGINT,

    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);
